[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm install -g serve && serve -s dist -l $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
